# Assignments for day 1

This notebook contains some assignments (or puzzles) you should try to solve to improve your understanding of python and make sure you understood the things you read in the examples notebook. Some of them are harder than others, don't feel bad if the solution seems unreachable or confusing! This is all part of the learning process. If you are stuck, feel free to ask your neighbor, the instructors, google, or even a Chat AI for help. 

It's OK if you don't get through everything. The last assignments especially are designed to challenge you, and if they feel overwhelming now, try coming back to them in a couple days - you may be surprised how much you've learned!

This assignment will not be graded and you don't need to turn it in (unless you want to)!

### 0. Bug Assignment:

In [3]:
#This cell has two bugs. First run it to see the error message, then try to fix the bugs one at a time.

print("I have fixed the bugs!")

I have fixed the bugs!


### 1. Variables assignment: radians/degrees
Create a variable called "deg2rad" that will convert degrees into radians whenever you multiply it by a value in degrees. For example, we want this to work correctly for any value of `number_in_degrees`:

    number_in_radians = number_in_degrees * deg2rad

Test your work by demonstrating that 180 degrees is equal to pi radians.

Then compute 1 degree in radians, and 1 radian in degrees.

Hint: radians = degrees * pi / 180 


In [4]:
import numpy as np

# enter a number in degrees:
number_in_degrees = 1.5

#here is our conversion factor:
deg2rad = np.pi/180

# do the conversion by multiplying
number_in_radians = number_in_degrees * deg2rad
print(number_in_degrees, 'degrees is', number_in_radians, 'radians')

# do the backwards conversion by dividing
ndeg_again = number_in_radians / deg2rad
print('back to degrees:',ndeg_again)

1.5 degrees is 0.026179938779914945 radians
back to degrees: 1.5


### 2. Numbers assignment
Write a function that will calculate the time that a signal takes to reach us from a GPS satellite, given the speed of light is roughly 3 x 10^8 meters/second. The altitude of the GPS satellite above the surface of Earth is 20,000 kilometers. 
You have the following tasks

(a) Define a variable for the speed of light, using scientific notation. In python this is done with 'e'. For example, `4.34e5` is equal to 434,000


In [6]:
c = 2.99e8

(b) Define a variable for the altitude of the GPS satellite, in meters, also using scientific notation (be careful of units here!)

 

In [7]:
h_meters = 20000*1000

 (c) Use the formula Time = Distance/Velocity, to calculate the time required by the signal to reach the Earth from the GPS satellite Assign the result to a new variable and print out the result.



In [8]:
time = h_meters/c
print(time)

0.06688963210702341


### 3. String assignment: 
Using the altitude and travel-time variables you calculated in part 2 above, print out the time traveled by the signal as a nicely formatted sentence:

    The time taken by the signal from a GPS satellite at an altitude of XXXX km to reach the Earth is X.XXXXX seconds.

  TIP: to print a variable using print() use the following syntax, where %f is the place-holder for a floating point variable, given with %variable at the end of the line:


      print ('the variable value is %f' %value) 
      
You can use other formatting options: %s for strings, and %d for integers. If you want to include more than one variable, you can list them in parentheses:


      print ('the first value is %f, the second is %d' %(value1,value2)) 
      
Finally, for floating point values you can control the number of values after the decimal point with e.g. "%.2f" for 2 decimal values.

Note, this is only one way of generating nicely formatted strings. Check out this page for (much) more information if you are interested: https://realpython.com/python-string-formatting/

In [9]:
h_km = h_meters/1000
print('The time taken by the signal from a GPS satellite at an altitude of %.1e km to reach the Earth is %.3f seconds.' %(h_km,time))

The time taken by the signal from a GPS satellite at an altitude of 2.0e+04 km to reach the Earth is 0.067 seconds.


### 4. Expression assignment
Define a variable, then create an expression that determines whether one computation done with that variable is larger than or smaller than another one. Your expression should return either "True" or "False" and save that value to a new variable. Then print out both the value and the type of that variable.

In [10]:
myvar = 1
op1 = myvar/2
op2 = myvar/2

op1isbigger = op1!=op2

print(op1isbigger)
print(type(op1isbigger))


False
<class 'bool'>


### 5. List assignment: 

a. Add 'kiwi' to the following list, before 'cherry', and print out the result

In [11]:
thislist = ["apple", "banana", "cherry"]
thislist.insert(2, "kiwi")
print(thislist)

['apple', 'banana', 'kiwi', 'cherry']


b. Create a list containing days of the week (starting with Sunday). Create a variable called "dayNum" that stores an integer from 1-7, then print out that day of the week. Note that dayNum=1 should print out Sunday - you will have to deal with the zero-indexing issue of Python!

In [13]:
days=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']
dayNum = 1
days[dayNum-1]

'Sunday'

### 6. Array assignment: Create a 3x3 array, and print out only the middle column.

In [15]:
myarray = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(myarray)
print('the middle column is:')
print(myarray[:,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
the middle column is:
[2 5 8]


### 7. Conditionals assignment:
Create a 2x2 numpy array, then compare the [0,0] and [1,1] elements of the array, and give a message about which is larger.

In [17]:
myarray = np.array([[4,2],[4,5]])

if myarray[0,0] > myarray[1,1]:
    print("element [0,0] is greater than element [1,1]")
else:
    print("element [1,1] is greater than or equal to element [0,0]")

element [1,1] is greater than or equal to element [0,0]


### 8. Loops assignment:
a. Create a nested for loop (two for loops inside each other) that populate the values of a 5x5 numpy array with the product of the two array index values. E.g:

    myarray[i,j] = i*j
    
Hint: we will first need to create a blank array of size 5x5. To do this, we use the following syntax:

    myarray=np.zeros((5,5))

In [18]:
myarray=np.zeros((5,5))

for i in range(5):
    for j in range(5):
        myarray[i,j] = i*j
        
print(myarray)

[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  2.  4.  6.  8.]
 [ 0.  3.  6.  9. 12.]
 [ 0.  4.  8. 12. 16.]]


b. Use a while loop to keep rolling a dice, and only stop when you roll a 6. To roll a dice from 1 to 6 in python, we can use:

    a = np.random.randint(1,7)

**Warning**: When trying out while loops, user beware! If you cause a bug that makes it run forever, use the square "stop" button at the top of the page.

**Note**: It's a good idea to use more informative variable names. Instead of calling your dice roll "a", give it a more informative name. This is a good habit to get into early on!

In [21]:
roll=0
while roll != 6:
    roll = np.random.randint(1,7)
    print(roll)
    
print("done")

5
1
2
1
3
4
6
done


### 9. Functions assignment: 
With all you've learned so far, you are now able to write some more or less fully-fledged programs! Here are a few exercises to practice your function mastery. For each one, give the function a sensible name, and test it with a few different inputs to make sure it works as you expect. 

a. Write a function that accepts 2 inputs: a string, and a number. The function should use a loop to print out the input string the specified number of times. Then call the function, using your name and favorite number as the input

In [22]:
def myFunction(mystring,mynumber):
    if not type(mynumber) == int:
        print("not an integer! silly you")
        return False
    for i in range(mynumber):
        print(mystring)
    return True
        
result = myFunction('Eric',5)
print(result)

Eric
Eric
Eric
Eric
Eric
True


In [93]:
True.

6

b. Convert your answer to question 2 above into a function called "deg2rad" that will convert any number input in degrees to radians
      
Hint: to use a more exact value of "pi", you have to import numpy as np. Then you can use "np.pi"


In [23]:
def deg2rad(deg):
    #return deg * np.pi/180
    return 1,2
    
r,s = deg2rad(180)
print(r)
print(s)

1
2


c. Write a function that will convert geographic coordinates in degree (D), minute (M), second (S) to decimal degrees format (DMS to DD.DDDD)
    
      Hint: 1 minute = 1/60 degree, 1 second = 1/3600  degree

In [27]:
def dms2decimal(d,m,s):
    return d + m/60 + s/3600

print(dms2decimal(5,30,0))

5.5


d. (Complicated!) Write a function that will input day, month, year and output day of year

   Tricky: beware of leap years, which are any years that can be exactly divided by 4, but not by 100 - i.e. 2004 is a leap year but 2000 is not.
   
   Python has a 'modulo' function that will tell you if a number is exactly divisible: for example, try 2015 % 4, and 2016 % 4
   

In [3]:
def juliandate(year,month,day):
    # first decide if the year is a leap year:
    if year % 4 ==0 and year % 100 !=0:
        isleap = True
    else:
        isleap = False
    monthdays = [31,28,31,30,31,30,31,31,30,31,30,31]
    jdate = day + sum(monthdays[:month-1])
    if isleap and month > 2:
        jdate = jdate + 1
    return jdate

# this test case should be 365
print(juliandate(2015,12,31))

# this test case should be 366
print(juliandate(2020,12,31))


365
366


e. Extra credit: Re-do problem d, but using the built-in python module 'datetime'. Use google to find the manual for the datetime module. You may find the code is much shorter!

In [8]:
import datetime

def juliandate_datetime(year,month,day):
    date_object = datetime.datetime(year, month, day)
    julian_date = date_object.timetuple().tm_yday
    return julian_date

# this test case should be 365
print(juliandate_datetime(2015,12,31))

# this test case should be 366
print(juliandate_datetime(2020,12,31))


365
366


### 10. Optional Assignment: modules

Make a module that contains a function that computes distance on a sphere by implementing one of the distance algorithms from https://en.wikipedia.org/wiki/Great-circle_distance.

Then import the module here, and compute the distance between Albuquerque (Lon, Lat: -106.62, 35.08) and your dream vacation destination.


### 11. Optional Assignment: programming challenges!
Try a programming challenge from 
https://www.codecademy.com/resources/blog/python-code-challenges-for-beginners/, or https://pythonprinciples.com/challenges/.